### ISSUE TITLE
Utools 不能同步到坚果云。。

### ISSUE THREAD

**Issue by kafeihack** [SUNbrightness/mypd#1]
Utools 不能同步到坚果云。。

**Comment by SUNbrightness** [comment]
是指什么不能同步?,账号密码保存后,无法同步到坚果云?

**Comment by kafeihack** [comment]
输入URL 账号密码   设置密码  初始化成功后，新建文件夹   新建账号密码   都无法同步到坚果云。如果utools重启，甚至需要重新输入url账号密码。。。重新设置密码。

**Comment by kafeihack** [comment]
在MAC 和  windows上面测试  都不能同步。

**Comment by SUNbrightness** [comment]
先新建一个文件夹,
1,输入新的文件夹名称,
2.点下面的加号,

选中新建的文件夹,填充账号信息,然后点提交.
你是不是再没有选中文件夹的情况下提交账号信息了?


如果utools重启，甚至需要重新输入url账号密码.
这个我会尽快修复的.

**Comment by SUNbrightness** [comment]
@kafeihack 感谢反馈,问题2我会尽快修复的

**Comment by kafeihack** [comment]
是点击了下面的加号，而且选中了文件夹，然后在添加的账号密码信息，点击保存，也不能同步成功。

**Comment by SUNbrightness** [comment]
@kafeihack 我更新代码,并上传了1.2的utools安装包, utools正在审核.
